# -*- mode: ruby -*-
# vi: set ft=ruby :
# TODO service redis stop 出现以下错误
# /var/run/redis_6379.pid does not exist, process is not running
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
# 版本指定
Vagrant.require_version ">= 2.0.0"
# Vagrant.require_version ">= 1.3.5", "< 1.4.0"


#设置 vagrant 配置版本 2
Vagrant.configure("2") do |config|

  #使用 box 镜像版本
  # config.vm.box = "luciferliu/centos7.9"
  config.vm.box = "xiaoruizou/Anolis"
  config.vm.box_version = "8.8"
  # 启动超时时间，默认300
  config.vm.boot_timeout=600
  #常量 初始化虚拟机的个数
  $num_instances = 1
  # 开始ip 最后一位 减 1  240 239
  $ip_start = 240
  # # 指定 ssh 用户名
  # config.ssh.username = "vagrant"
  # # 不使用private key 方式，使用密码方式登录
  # config.ssh.password = "vagrant"
  # box 是否更新
  (1..$num_instances).each do |i|
    config.vm.define "ansible-#{i+$ip_start}-Anolis88" do |node|
      node.vm.box = "xiaoruizou/Anolis"
      node.vm.box_version = "8.8"
      
      #起始 ip 减 1
      # 251
      ip = "172.31.255.#{i+$ip_start}"
      hostname = "ansible-#{i+$ip_start}-Anolis88"
      
      node.vm.hostname = hostname
      
      # Anolis OS 8.x 网络配置方式
      node.vm.network "private_network", ip: ip, auto_config: false
      
      # 自动配置脚本 (Anolis OS 8.x 需要)
      # 同时设置 hostname 和网络
      # privileged: true 确保以 root 权限执行
      node.vm.provision "shell", run: "always", privileged: true, inline: <<-SHELL
        # 设置主机名
        HOSTNAME="#{hostname}"
        IP_ADDR="#{ip}"
        
        echo "========================================"
        echo "配置主机: $HOSTNAME"
        echo "配置 IP: $IP_ADDR"
        echo "========================================"
        
        # 设置 hostname
        hostnamectl set-hostname "$HOSTNAME"
        echo "主机名已设置为: $HOSTNAME"
        
        # 配置 enp0s8 网卡 IP
        echo "配置网卡 enp0s8..."
        
        if ip link show enp0s8 &> /dev/null; then
          # 删除可能存在的旧连接
          nmcli con delete enp0s8 2>/dev/null
          
          # 添加新的以太网连接
          nmcli con add type ethernet con-name enp0s8 ifname enp0s8 ip4 "${IP_ADDR}/24"
          
          # 启用连接
          nmcli con up enp0s8
          
          echo "网络配置完成"
        else
          echo "警告: 网卡 enp0s8 不存在"
        fi
        
        echo "========================================"
        echo "配置结果:"
        echo "主机名: $(hostname)"
        ip addr show enp0s8 2>/dev/null || echo "enp0s8 配置失败"
        echo "========================================"
      SHELL
      
      # node.vm.synced_folder "/Users/DuffQiu/share", "/home/vagrant/share"
      # TODO 不同的虚机设置不同的同步目录
      node.vm.synced_folder "./Synced" , "/Synced"
      # node.vm.synced_folder "/Users/husx/data/git/github/husxwy/ansible", "/ansible-mac"
      #TODO 这里不同服务启动不同端口
      # 2181 cline端提供服务
      # node.vm.network "forwarded_port", guest: "#{i+6999}", host: "#{i+6999}"
      # node.vm.network "forwarded_port", guest: "#{i+16999}", host: "#{i+16999}"
      node.vm.network "forwarded_port", guest: "#{i+3999}", host: "#{i+3999}"
      node.vm.network "forwarded_port", guest: "#{i+3305}", host: "#{i+3305}"
      node.vm.network "forwarded_port", guest: "#{i+6378}", host: "#{i+6378}"
      # 3888 选举leader使用
      # node.vm.network "forwarded_port", guest: "#{i+7002}", host: "#{i+7002}"
      # 集群总线端口为16379 （端口 + 10000 如 如redis端口为6379 则集群总线端口为16379）
      # node.vm.network "forwarded_port", guest: "#{i+17002}", host: "#{i+17002}"
      # # 2888 集群内机器通讯使用（Leader监听此端口）
      # node.vm.network "forwarded_port", guest: "#{i+2887}", host: "#{i+2887}"
      
      # 挂载新的磁盘 
      # 先设置环境变量  export VAGRANT_EXPERIMENTAL="disks"
      # extra_storage 是镜像文件名 extra_storage.vdi
      # 需要手动挂载磁盘
      # node.vm.disk :disk, size: "10GB", name: "extra_storage"


      # centos 7 配置脚本
      # node.vm.provision "shell", path: "/Users/husx/data/git/github/husxwy/ansible/vagrant/0bash/auth.sh"
      # 
      # config.vm.provision "shell", path: "bash/redis.sh"
      # redis-trib 有参数输入问题
      # config.vm.provision "shell", path: "bash/redis-trib.sh"
      
      node.vm.provider "virtualbox" do |vb|
      #   # Display the VirtualBox GUI when booting the machine
      #   vb.gui = true
      #
      #   # Customize the amount of memory on the VM:
        vb.memory = "4096"
        vb.cpus = 1
        vb.name = "ansible-#{i+$ip_start}-Anolis88"  # virtualbox 文件夹名
      end
    end
  end
end
